spring.application.name=canciones
# ===================================================================
# CONEXIÓN A BASE DE DATOS MYSQL (canciones_db)
# ===================================================================
spring.datasource.url=jdbc:mysql://localhost:3306/canciones_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=7*nB77f79Il357
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===================================================================
# CONFIGURACIÓN DE HIBERNATE / JPA
# ===================================================================
# update: verifica la tabla en MySQL. Si falta una columna, la crea. No borra datos existentes.
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola de STS el código SQL que Java genera por detrás
spring.jpa.show-sql=true

# ===================================================================
# CONFIGURACIÓN DEL RESOLVER PARA VISTAS .JSP
# ===================================================================
# Le dice al controlador dónde buscar físicamente los archivos web
spring.mvc.view.prefix=/WEB-INF/

# Permite que los formularios HTML nativos (<form>) ejecuten peticiones PUT, DELETE o PATCH 
# mediante un parámetro oculto llamado "_method", superando la restricción nativa del navegador.
spring.mvc.hiddenmethod.filter.enabled=true